### ISSUE TITLE
Cannot access top area of oled display

### ISSUE THREAD

**Issue by einsteinx2** [baoshi/ESP-I2C-OLED#2]
I have one of these two color 128x64 oled displays: http://www.aliexpress.com/snapshot/6527585548.html

When I used ug8lib with an arduino, the top area which is yellow was accessed just by writing to the first few rows of the display. However with the ESP-I2C-OLED library, writing to position 0,0 seems to start in the blue section and the yellow top section is inaccessible.

As far as I understood it, the display is just a regular 128x64 monochrome display where the first 10 rows or so happen to be yellow instead of blue. Now sure why the library seems to think row 0 starts in the blue area. 

Any ideas?

**Comment by baoshi** [comment]
I have encounter this before. The reason being the OLED panel is not using a SSD1306 controller. It is, most probably, SH1106. Their instruction set are slightly different. I can do some investigation, but first I need to find the SH1106 panel ;)

**Comment by einsteinx2** [comment]
I have 3 of them, I'd be happy to drop one in the mail for you tomorrow.

**Comment by einsteinx2** [comment]
Got it working! By chance the first thing I tried was to comment out the following lines in init_OLED, and it resolved the issue!

`//sendcommand(0xA8);            //SSD1306_SETMULTIPLEX`
`//sendcommand(0x2F); //--1/48 duty    //NEW!!!`

**Comment by einsteinx2** [comment]
Actually, looks like it's only this line that must be removed for it to work:

`sendcommand(0xA8);            //SSD1306_SETMULTIPLEX`
